version: '3.5'

services:
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always

  web:
    build: .
    env_file: .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - .:/app/
    command: >
          sh -c " 
          python manage.py makemigrations 
          && python manage.py migrate 
          && python manage.py runserver ${IP}:${PORT}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - memcached