# Generated by Django 5.1.1 on 2024-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('num_of_views', models.IntegerField(default=0)),
            ],
        ),
    ]
