# Generated by Django 5.1.1 on 2024-10-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='num_of_views',
        ),
    ]
