# Generated by Django 5.1.1 on 2024-10-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='identifier',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='url',
            new_name='url_key',
        ),
    ]
