# Generated by Django 5.1.1 on 2024-10-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_rename_identifier_note_key_rename_url_note_url_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_read',
        ),
    ]
