# Generated by Django 5.1.1 on 2024-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_remove_note_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='url_key',
            field=models.CharField(max_length=45),
        ),
    ]
