# Generated by Django 5.1.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_start_date_alter_note_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
