# Generated by Django 5.1.1 on 2024-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_note_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
